name: gstcefsrc pull request test

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Run gstcefsrc tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes libunwind-dev
          sudo apt-get install --yes libgstreamer1.0-0 libgstreamer-plugins-base1.0-dev gstreamer1.0-tools xvfb

      - name: Cache
        id: cache-cmake
        uses: actions/cache@v3
        with:
          path: |
            build/
            third_party/
          key: ${{ hashFiles('cmake/DownloadCEF.cmake') }}-${{ hashFiles('CMakeLists.txt') }}-cache

      - name: cmake
        if: steps.cache-cmake.outputs.cache-hit != 'true'
        run: |
          mkdir -p build && cd build
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..

      - name: make
        run: |
          cd build
          make -j

      - name: test plugin load
        run: |
          export GST_PLUGIN_PATH="$PWD/build/Release:${GST_PLUGIN_PATH}"
          gst-inspect-1.0 cefsrc

      - name: test startup pipeline
        run: |
          export GST_PLUGIN_PATH="$PWD/build/Release:${GST_PLUGIN_PATH}"
          timeout 120s xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" \
            gst-launch-1.0 -e \
            cefsrc listen-for-js-signals=true url="file://$PWD/html/ready_test.html" ! \
            "video/x-raw,width=1280,height=720,framerate=30/1" ! \
            fakesink sync=false
